sudo: false

language: node_js
node_js:
  - stable
  - 7
  - 6
  - 5
  - 4

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

