sudo: false

dist: precise

language: node_js
node_js:
  - stable
  - 7
  - 6

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

deploy:
  - provider: npm
    email: code@tommilligan.net
    api_key: $NPM_API_KEY
    on:
      branch: react-router-scroll-internal-history
      tags: true
      condition: $TRAVIS_NODE_VERSION = 7 && "$BROWSER" == "ChromeCi"

notifications:
  email: false
